- id: 1
  title: Cappuccino
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/cappuccino.jpg
  price: 2.99
  weight: 100
  maximum-quantity: 10
  url: /

- id: 2
  title: Espresso
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/espresso.jpg
  price: 3.99
  weight: 100
  maximum-quantity: 5
  url: /

- id: 3
  title: Mocha
  description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  image: /assets/images/black-coffee.jpg
  price: 2.59
  weight: 100
  maximum-quantity: 3
  url: /
